services:
  web:
    image: node:22-alpine
    restart: always
    ports:
      - 80:3000
    working_dir: /data
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ''
    volumes:
      - .:/data:ro
    command: bash -c "npm i"
    entrypoint: ["npm", "run", "host"]
    depends_on:
      - db

  db:
    image: mariadb:noble
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
